services:
  llm-service-one:
    build:
      context: ./LLM/
      dockerfile: llm.Dockerfile

  llm-service-two:
    build:
      context: ./LLM/
      dockerfile: llm.Dockerfile

  llm-service-three:
    build:
      context: ./LLM/
      dockerfile: llm.Dockerfile

  backend:
    build:
      context: ./Backend/
      dockerfile: backend.Dockerfile

  frontend:
    build:
      context: ./Frontend/
      dockerfile: frontend.Dockerfile

