x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]

  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    ports:
      - "5001:80"
    depends_on:
      - qdrant
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  model_cache:
  qdrant_data:
  llm_cache: