services:
  llm-service:
    command: sh -c 'uvicorn main:app --host 0.0.0.0 --port {-p 8000}'
    env_file:
      - .env
    environment:
      - QDRANT_PORT=6333
      - QDRANT_HOST=qdrant
      - QDRANT_USE_HTTPS=false
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      - ./LLM/:/app
      - ./LLM/:/qdrant/config

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_BASE_API_URL=http://localhost:5001/api
      - VITE_SIGNALR_HUB_URL=http://localhost:5001/progressHub
