name: Smart Excel Analyzer

x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    volumes:
      - qdrant_data:/qdrant/data
    env_file:
      - .env
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]

  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    env_file:
      - ./LLM/.env
    depends_on:
      - qdrant
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
    depends_on:
      - qdrant
      - llm-service

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      - backend

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - smart-excel-network
    depends_on:
      - frontend
      - backend

networks:
  smart-excel-network:
    driver: overlay
    attachable: true

volumes:
  model_cache:
  qdrant_data: