services:
  qdrant:
    env_file:
      - .env
    ports:
      - "6333:6333"

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_BASE_API_URL=http://localhost:5001/api
      - VITE_SIGNALR_HUB_URL=http://localhost:5001/progressHub
    ports:
      - "3000:3000"

volumes:
  model_cache:
  qdrant_data:
  llm_cache: