services:
  llm-service:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface
    deploy:
      replicas: 6
    environment:
      - PORT=${PORT:-8000}
    ports:
      - "8000-8005:8000"

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_API_URL=http://localhost:5001