name: Smart Excel Analyzer

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./Frontend/traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - smart-excel-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    volumes:
      - qdrant_data:/qdrant/data
      - ./qdrant_config.yml:/qdrant/config/qdrant_config.yaml
    env_file:
      - .env
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=false"

  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    env_file:
      - ./LLM/.env
    depends_on:
      - qdrant
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=false"

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    networks:
      - smart-excel-network
    depends_on:
      - qdrant
      - llm-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"
      - "traefik.http.routers.backend.entrypoints=web"

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - smart-excel-network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=web"

networks:
  smart-excel-network:
    driver: overlay
    attachable: true

volumes:
  model_cache:
  qdrant_data: