name: Smart Excel Analyzer

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:81"
    ports:
      - "81:81" 
      - "8080:8080" # Dashboard - helpful
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=81"
      - "traefik.http.routers.traefik.entrypoints=web"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - smart-excel-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - smart-excel-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    volumes:
      - qdrant_data:/qdrant/data
      - ./qdrant_config.yml:/qdrant/config/qdrant_config.yaml
    env_file:
      - .env
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`traefik`) && PathPrefix(`/qdrant`)"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
      - "traefik.http.routers.qdrant.entrypoints=web"

  llm-service-one:
    image: fivemowner/smart-excel-analyzer-llm:latest
    container_name: llm-service-one
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-service-one.rule=Host(`traefik`) && PathPrefix(`/llm-service-one`)"
      - "traefik.http.services.llm-service-one.loadbalancer.server.port=8000"
      - "traefik.http.routers.llm-service-one.entrypoints=web"

  llm-service-two:
    image: fivemowner/smart-excel-analyzer-llm:latest
    container_name: llm-service-two
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-service-two.rule=Host(`traefik`) && PathPrefix(`/llm-service-two`)"
      - "traefik.http.services.llm-service-two.loadbalancer.server.port=8001"
      - "traefik.http.routers.llm-service-two.entrypoints=web"

  llm-service-three:
    image: fivemowner/smart-excel-analyzer-llm:latest
    container_name: llm-service-three
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - smart-excel-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-service-three.rule=Host(`traefik`) && PathPrefix(`/llm-service-three`)"
      - "traefik.http.services.llm-service-three.loadbalancer.server.port=8002"
      - "traefik.http.routers.llm-service-three.entrypoints=web"

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ./Backend:/src
    env_file:
      - .env
    networks:
      - smart-excel-network
    depends_on:
      - qdrant
      - llm-service-three
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`traefik`) && PathPrefix(`/api`) && PathPrefix(`/progressHub`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"
      - "traefik.http.routers.backend.entrypoints=web"

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    container_name: frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_BASE_API_URL=http://localhost:5001/api
      - VITE_SIGNALR_HUB_URL=http://localhost:5000/progressHub
    networks:
      - smart-excel-network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`traefik`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=web"

networks:
  smart-excel-network:
    driver: bridge

volumes:
  model_cache:
  qdrant_data: