x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 3
  start_period: 40s

x-llm-service: &llm-service
  image: fivemowner/smart-excel-analyzer-llm:latest
  env_file:
    - .env
  environment:
    - QDRANT_PORT=6333
    - QDRANT_HOST=qdrant
    - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
    - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    - QDRANT_API_KEY=${QDRANT_API_KEY}
  command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
  healthcheck:
    <<: *default-healthcheck
    test: curl -f http://localhost:${PORT:-8000}/health
  depends_on:
    - qdrant

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/production.yaml"
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
    env_file:
      - .env

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    ports:
      - "5001:80"
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    depends_on:
      - qdrant
      - llm-service-0
      - llm-service-1
      - llm-service-2
      - llm-service-3
      - llm-service-4
      - llm-service-5
    env_file:
      - .env

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  model_cache:
  qdrant_data: