services:
  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    env_file:
      - .env
    environment:
      - QDRANT_PORT=6333
      - QDRANT_HOST=qdrant
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT}

  llm-service-0:
    extends:
      service: llm-service
    environment:
      - PORT=8000
    ports:
      - "8000:8000"

  llm-service-1:
    extends:
      service: llm-service
    environment:
      - PORT=8001
    ports:
      - "8001:8000"

  llm-service-2:
    extends:
      service: llm-service
    environment:
      - PORT=8002
    ports:
      - "8002:8000"

  llm-service-3:
    extends:
      service: llm-service
    environment:
      - PORT=8003
    ports:
      - "8003:8000"

  llm-service-4:
    extends:
      service: llm-service
    environment:
      - PORT=8004
    ports:
      - "8004:8000"

  llm-service-5:
    extends:
      service: llm-service
    environment:
      - PORT=8005
    ports:
      - "8005:8000"

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_BASE_API_URL=http://localhost:5001/api
      - VITE_SIGNALR_HUB_URL=http://localhost:5001/progressHub