services:
  qdrant:
    volumes:
      - qdrant_data:/qdrant/storage
      - ./qdrant_config.yml:/qdrant/config/production.yml
    env_file:
      - .env

  llm-service-0:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  llm-service-1:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface
    
  llm-service-2:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface
    
  llm-service-3:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface
    
  llm-service-4:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface
    
  llm-service-5:
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface
    
  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_API_URL=http://localhost:5001