services:
  llm-service-0:
    extends:
      service: llm-service
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  llm-service-1:
    extends:
      service: llm-service
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  llm-service-2:
    extends:
      service: llm-service
    environment:
      - PORT=8002
    ports:
      - "8002:8002"
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  llm-service-3:
    extends:
      service: llm-service
    environment:
      - PORT=8003
    ports:
      - "8003:8003"
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  llm-service-4:
    extends:
      service: llm-service
    environment:
      - PORT=8004
    ports:
      - "8004:8004"
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  llm-service-5:
    extends:
      service: llm-service
    environment:
      - PORT=8005
    ports:
      - "8005:8005"
    volumes:
      - ./LLM:/app
      - model_cache:/root/.cache/huggingface

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_API_URL=http://localhost:5001