x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./Frontend/traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - smart-excel-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  qdrant:
    image: qdrant/qdrant:latest
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    volumes:
      - qdrant_data:/qdrant/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.qdrant == true
          - node.Hostname == traefik
          # - node.loadbalancer.server.port == 6333

  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - ./qdrant_data:/qdrant/data
    env_file:
      - ./LLM/.env
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    depends_on:
      - qdrant
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    volumes:
      - ./backend:/app
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    depends_on:
      - qdrant
      - llm-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.backend.entrypoints=web"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    env_file:
      - ./Frontend/.env
    environment:
      - REACT_APP_BACKEND_URL=backend
    volumes:
      - ./Frontend/src:/app/src
    ports:
      - "3000:3000"
    logging:
      <<: *default-logging
    networks:
      - smart-excel-network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=web"
    deploy:
      endpoint_mode: vip
      restart_policy:
        condition: on-failure

networks:
  smart-excel-network:
    driver: overlay

volumes:
  model_cache:
  qdrant_data:
  llm_cache: