services:
  llm-service:
    command: sh -c 'export PORT=$((8000 + DOCKER_SERVICE_REPLICA_ID)) && uvicorn main:app --host 0.0.0.0 --port $${PORT}'
    ports:
      - '${PORT_BASE:-8000}-${PORT_MAX:-8005}:8000-8005'

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_BASE_API_URL=http://localhost:5001/api
      - VITE_SIGNALR_HUB_URL=http://localhost:5001/progressHub