x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  qdrant:
    image: qdrant/qdrant:latest
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
    logging:
      <<: *default-logging
    volumes:
      - qdrant_data:/qdrant/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.qdrant == true

  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - ./qdrant_data:/qdrant/data
    env_file:
      - ./LLM/.env
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health
    logging:
      <<: *default-logging
    depends_on:
      - qdrant
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    volumes:
      - ./backend:/app
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    logging:
      <<: *default-logging
    depends_on:
      - qdrant
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend/src:/app/src
    ports:
      - "3000:3000"
    logging:
      <<: *default-logging
    deploy:
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

volumes:
  model_cache:
  qdrant_data:
  llm_cache:
