x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - smart-excel-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - smart-excel-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - smart-excel-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  qdrant:
    image: qdrant/qdrant:latest
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    volumes:
      - qdrant_data:/qdrant/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`traefik`) && PathPrefix(`/qdrant`)"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
      - "traefik.http.routers.qdrant.entrypoints=web"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
          - node.labels.qdrant == true

  llm-service-one:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-service-one.rule=Host(`traefik`) && PathPrefix(`/llm-service-one`)"
      - "traefik.http.services.llm-service-one.loadbalancer.server.port=8000"
      - "traefik.http.routers.llm-service-one.entrypoints=web"

  llm-service-two:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-service-two.rule=Host(`traefik`) && PathPrefix(`/llm-service-two`)"
      - "traefik.http.services.llm-service-two.loadbalancer.server.port=8001"
      - "traefik.http.routers.llm-service-two.entrypoints=web"

  llm-service-three:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-service-three.rule=Host(`traefik`) && PathPrefix(`/llm-service-three`)"
      - "traefik.http.services.llm-service-three.loadbalancer.server.port=8002"
      - "traefik.http.routers.llm-service-three.entrypoints=web"

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    volumes:
      - ./Backend:/src
    env_file:
      - .env
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
    networks:
      - smart-excel-network
    logging:
      <<: *default-logging
    depends_on:
      - qdrant
      - llm-service-three
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`traefik`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"
      - "traefik.http.routers.backend.entrypoints=web"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_BASE_API_URL=http://backend/api
      - VITE_SIGNALR_HUB_URL=http://backend/progressHub
    networks:
      - smart-excel-network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`traefik`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=web"
    deploy:
      endpoint_mode: vip
      restart_policy:
        condition: on-failure

networks:
  smart-excel-network:
    driver: overlay

volumes:
  model_cache:
  qdrant_data:
  llm_cache: