name: Smart Excel File Analyzer Docker Compose Network

x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]

  llm-service-0:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health

  llm-service-1:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
    ports:
      - "8001:8000"
    depends_on:
      - qdrant
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health

  llm-service-2:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
    ports:
      - "8002:8000"
    depends_on:
      - qdrant
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    ports:
      - "5001:80"
    depends_on:
      - qdrant
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend