services:
  qdrant:
    env_file:
      - .env

  llm-service:
    env_file:
      - .env
    volumes:
      - ./LLM/:/app
      - ./LLM/:/qdrant/config

  backend:
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_BASE_API_URL=http://localhost:5001/api
      - VITE_SIGNALR_HUB_URL=http://localhost:5001/progressHub

volumes:
  model_cache:
  qdrant_data:
  llm_cache:
