services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 40s

  llm-service-0:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - model_cache:/root/.cache/huggingface
      - ./LLM:/app
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 40s

  llm-service-1:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - model_cache:/root/.cache/huggingface
      - ./LLM:/app
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  llm-service-2:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8002:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    volumes:
      - model_cache:/root/.cache/huggingface
      - ./LLM:/app
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  llm-service-3:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8003:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    volumes:
      - model_cache:/root/.cache/huggingface
      - ./LLM:/app
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  llm-service-4:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8004:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8004
    volumes:
      - model_cache:/root/.cache/huggingface
      - ./LLM:/app
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  llm-service-5:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8005:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    volumes:
      - model_cache:/root/.cache/huggingface
      - ./LLM:/app
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "5001:80"
    environment:
      # ASP.NET Core settings
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # LLMServiceOptions
      - LLMServiceOptions__COMPUTE_BATCH_SIZE=500
      - LLMServiceOptions__LLM_SERVICE_URL=http://llm-service-0:8000
      - LLMServiceOptions__LLM_SERVICE_URLS=http://llm-service-0:8000,http://llm-service-1:8001,http://llm-service-2:8002,http://llm-service-3:8003,http://llm-service-4:8004,http://llm-service-5:8005
      # DatabaseOptions
      - DatabaseOptions__SAVE_BATCH_SIZE=100
      - DatabaseOptions__MAX_CONNECTION_COUNT=200
      - DatabaseOptions__MAX_RETRY_COUNT=3
      - DatabaseOptions__ConnectionString=http://qdrant:6333
      - DatabaseOptions__DatabaseName=documents
    depends_on:
      - llm-service-0
      - llm-service-1
      - llm-service-2
      - llm-service-3
      - llm-service-4
      - llm-service-5
      - qdrant
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BASE_API_URL=http://localhost:5001
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  model_cache:
  qdrant_data:

  # Uncomment the following section to use PostgreSQL for some type of audit logging down the line
  # db:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: smartexcelanalyzer
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U admin -d smartexcelanalyzer"]
  #     interval: 120s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    #   interval: 120s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: smartexcelanalyzer
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodata:/data/db