version: '3.8'

services:
  llm-service:
    build:
      context: ./LLM
      dockerfile: llm.Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - TEXT_GENERATION_MODEL=facebook/bart-large-cnn
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - DB_CONNECTION_STRING="dbname=smartexcelanalyzer user=admin password=password host=db sslmode=disable"

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LLM_SERVICE_URL=http://llm-service:5000
      - DB_CONNECTION_STRING="Host=db;Username=admin;Password=password;Database=smartexcelanalyzer"
    depends_on:
      - llm-service
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BASE_API_URL=http://localhost:5001
    depends_on:
      - backend
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: smartexcelanalyzer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smartexcelanalyzer"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: