name: Smart Excel Analyzer

x-healthcheck: &default-healthcheck
  interval: 120s
  timeout: 10s
  retries: 200
  start_period: 40s

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    command:
      - "./qdrant"
      - "--config-path"
      - "/qdrant/config/qdrant_config.yaml"
    volumes:
      - qdrant_data:/qdrant/data
    env_file:
      - .env
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]

  llm-service:
    image: fivemowner/smart-excel-analyzer-llm:latest
    volumes:
      - ./LLM:/app
      - /model_cache:/app/model_cache
    env_file:
      - ./LLM/.env
    depends_on:
      - qdrant
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: curl -f http://localhost:8000/health

  backend:
    image: fivemowner/smart-excel-analyzer-backend:latest
    volumes:
      - ./Backend:/app
      - /app/obj
      - /app/bin
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    depends_on:
      - qdrant
      - llm-service

  frontend:
    image: fivemowner/smart-excel-analyzer-frontend:latest
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - smart-excel-network
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - smart-excel-network
    depends_on:
      - backend
      - frontend

networks:
  smart-excel-network:
    driver: overlay
    attachable: true

volumes:
  model_cache:
  qdrant_data: