version: '3.8'

services:
  llm-service:
    build: 
      context: ./LLM
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - llm-service

  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  models: