global:
  scrape_interval: 30s 

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:81'] 

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5001'] 

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 
