service:
  api_key: ${QDRANT_API_KEY}
qdrant:
  api_key: ${QDRANT_API_KEY}
  port: ${DatabaseOptions__PORT}
  host: ${DatabaseOptions__HOST}
  config_path: /qdrant/config/production.yaml
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:${DatabaseOptions__PORT}/health"]
