trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - main

jobs:
- job: Build and Run Docker Compose
  displayName: 'Build and Run Docker Compose'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: DockerCompose@1
    displayName: 'Build and Run Docker Compose'
    inputs:
      containerregistry: '$(dockerRegistryServiceConnection)'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run services'
      detached: true

  - task: DockerCompose@1
    displayName: 'Tear Down Docker Compose'
    inputs:
      containerregistry: '$(dockerRegistryServiceConnection)'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Down'
      options: '--volumes'
    condition: always()