name: Build and Push Smart Excel Analyzer Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Upload repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: .
          retention-days: 1

  backend-build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/backend.Dockerfile
          push: true
          tags: fivemowner/smart-excel-analyzer-backend:latest

  frontend-build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Run Tests
        run: npm test
        working-directory: ./Frontend

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          file: ./Frontend/frontend.Dockerfile
          push: true
          tags: fivemowner/smart-excel-analyzer-frontend:latest

  llm-build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push LLM Service
        uses: docker/build-push-action@v4
        with:
          context: ./LLM
          file: ./LLM/llm.Dockerfile
          push: true
          tags: fivemowner/smart-excel-analyzer-llm:latest