name: Build and Push Smart Excel Analyzer Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Upload repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: .
          retention-days: 1
  
  run-tests:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --logger trx --results-directory ./TestResults --configuration Debug --collect "Code Coverage"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./TestResults/**/*.xml
          flags: unittests
          name: code-coverage-report
          fail_ci_if_error: true

  backend-build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/backend.Dockerfile

  frontend-build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          file: ./Frontend/frontend.Dockerfile
          push: true
          tags: fivemowner/smart-excel-analyzer-frontend:latest

  llm-build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push LLM Service
        uses: docker/build-push-action@v4
        with:
          context: ./LLM
          file: ./LLM/llm.Dockerfile
          push: true
          tags: fivemowner/smart-excel-analyzer-llm:latest
