name: Build and Push Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'Frontend/**'
  pull_request:
    branches: [ main ]  
    paths:
      - 'Frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install
      working-directory: ./Frontend
      
    - name: Run tests
      run: npm test
      working-directory: ./Frontend
      
    - name: Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./Frontend
        file: ./Frontend/frontend.Dockerfile
        push: true
        tags: fivemowner/smart-excel-analyzer-frontend:latest
