name: Update PR Description with All Other Workflow Statuses

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get Workflow Statuses
      id: get-status
      run: |
        # Get the status of all CI/CD workflows
        statuses=$(gh run list --json name,status,conclusion --jq '.[] | "\(.name): \(.status) (\(.conclusion))"')
        echo "statuses=$statuses" >> $GITHUB_ENV

    - name: Generate Badges
      id: generate-badges
      run: |
        statuses="${{ env.statuses }}"
        badges=""
        for status in $statuses; do
          name=$(echo $status | cut -d: -f1)
          conclusion=$(echo $status | cut -d\( -f2 | cut -d\) -f1)
          badge="![${name}](https://img.shields.io/badge/${name}-${conclusion}-brightgreen)"
          badges="${badges}\n${badge}"
        done
        echo "badges=$badges" >> $GITHUB_ENV

    - name: Update PR Description
      env:
        BADGES: ${{ env.badges }}
      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        pr_body=$(gh pr view $pr_number --json body --jq ..body)
        new_body="$pr_body\n\n### CI/CD Status\n$BADGES"
        gh pr edit $pr_number --body "$new_body"