name: Update PR Description with All Other Workflow Statuses

on:
  pull_request:
    types: [ 
        opened, 
        synchronize
    ] 

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install git cli
      run: sudo apt-get install gh

    - name: Authenticate git
      run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

    - name: Get CI/CD Status
      id: get-status
      run: |
        # Get the status of all CI/CD workflows
        statuses=$(gh run list --json name,status,conclusion --jq '.[] | "\(.name): \(.status) (\(.conclusion))"')
        echo "statuses=$statuses" >> $GITHUB_ENV

    - name: Update PR Description
      env:
        STATUSES: ${{ env.statuses }}
      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        pr_body=$(gh pr view $pr_number --json body --jq .body)
        new_body="$pr_body\n\n### CI/CD Status\n$STATUSES"
        gh pr edit $pr_number --body "$new_body"